#spring:
#  datasource:
#    url: jdbc:mysql://${zlt.datasource.ip}:${zlt.datasource.port}/platform-backend-server?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    username: ${zlt.datasource.username}
#    password: ${zlt.datasource.password}
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.central.platform.backend.model
#  global-config:
#    db-config:
#      id-type: auto

zlt:
  swagger:
    enabled: true
    title: 平台后端管理系统服
    description: 平台后端管理系统服接口文档
    version: 1.0
    base-package: com.central.backend.controller
  #cache-manager: configs: - key: menu second: 300
